version: "2.1"
services:
  config:
    build: config
    ports:
      - 8888:8888
      
  eureka-server:
    build: eureka-server
    
  apiGateway:
    build: apiGateway
    
  LoginService:
    build: LoginService
    
  MyChat:
    build: MyChat
    
    

